### ISSUE TITLE
lein datomic start & (weird logging)

### ISSUE THREAD

**Issue by boxxxie** [johnwayner/lein-datomic#1]
i named my db uri in the lein project.clj, however when i start the db via:

```
lein datomic start &
'data-dir' property not set, defaulting to 'data' in current directory
'log-dir' property not set, defaulting to 'log' in current directory
Starting datomic:free://localhost:4334/<DB-NAME>, storing data in: data ...
```

the output of the uri seems wierd. i looked at your code and couldn't find a ref to '<DB-NAME>' so i don't know where it is coming from, i also don't know if this is good or not? should i be worried that my db name isn't being printed out?

**Comment by boxxxie** [comment]
i wrote some tests against my initalized data, and they pass. so i'm not worried about my db not being created properly.
it may still be good to have a better output to the console upon startup.

**Comment by johnwayner** [comment]
That output message is from the transactor.  The transactor can handle any number of databases and that's why the url presented is generic.  The URI specified in the configuration is only used to load the schema files.
